name: Build TWRP for Samsung Galaxy A02

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: false
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install Build Dependencies & Fix Clang/Python Libs
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 libtinfo5 libncurses-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 python-is-python3 2to3 || true
        sudo ln -sf /usr/bin/python3 /usr/bin/python || true
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5 || true
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libncurses.so.6 /usr/lib/x86_64-linux-gnu/libncurses.so.5 || true

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Sync TWRP Minimal Source
      run: |
        mkdir twrp
        cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-9.0 --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree & Fix Python 2/3 Compatibility
      run: |
        cd twrp
        git clone https://github.com/twrpdtgen/android_device_samsung_a02.git device/samsung/a02
        # Tarafımızca tespit edilen tüm eski Python 2 print scriptlerini otomatik Python 3'e çevir
        find build/ -name "check_radio_versions.py" -exec 2to3 -w {} + || true
        find build/ -name "*.py" -exec 2to3 -w {} + || true

    - name: Build TWRP Image
      run: |
        cd twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_a02-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload TWRP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP_SM-A022F
        path: twrp/out/target/product/a02/*.img
